TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'ObisConcept.NeosBootstrap': TRUE

    userInterface:
      translation:
        autoInclude:
          'ObisConcept.NeosBootstrap': ['NodeTypes/*']