ObisConcept:
  includeFrontendAssets: true
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          ObisConcept.NeosBootstrap:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        ObisConcept.NeosBootstrap: true
